### DISCUSSION TITLE
How to remove vertical border of cells

### DISCUSSION THREAD

**Discussion by relyada** [Comcast/react-data-grid#2905] [Q&A]
Hi,

I would like to remove all vertical borders without using "pure css". Is there a way to doing this using makeStyles?

![image](https://user-images.githubusercontent.com/79521545/167119862-c985c2b6-5c3f-4913-8231-bf7854088621.png)

Thanks

**Comment by pgarbo** [comment]
Hi, 
I have the same problem, did you manage to resolve this?
Pawel

**Reply by NickyAlfEdge** [reply]
```css
.rdg-cell {
    border-left: none;
    border-right: none;
}
```
Horizontal lines only

```css
.rdg-cell[role='gridcell'] {
    border-left: none;
    border-right: none;
}
```
Horizontal lines only for non-header table rows

```css
.rdg-cell {
    border: none;
}
```
No lines
