### DISCUSSION TITLE
Data grid style conflict with tailwindbase

### DISCUSSION THREAD

**Discussion by robert-luoqing** [Comcast/react-data-grid#3674] [General]
## Describe the bug 
When I import Tailwind's style components into index.css, the grid's style changes unexpectedly and no longer appears as the default or preferred design. However, when I comment out @tailwind base;, the style reverts to normal.

Here is the code I'm using:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
Issue Screenshots
Unexpected style (with @tailwind base;)
![image](https://github.com/user-attachments/assets/3b61f2d8-14fc-4b85-8a62-7434a5b3b75d)
Normal style (without @tailwind base;)
![image](https://github.com/user-attachments/assets/3cc7a30f-5796-41f0-8782-aa16a7afb426)

Request for Help
How can I resolve this issue? I want to include @tailwind base; in my project but still maintain the normal style.

## To Reproduce 

Link to code example:

## Environment

- "react-data-grid": "^7.0.0-beta.47",
- `react`/`react-dom`: "^18.3.1",

**Comment by amanmahajan7** [comment]
Can you create a reproducible example?

**Comment by robert-luoqing** [comment]
Here is sample.
The reproduction step is as follows:
1. npx create-react-app data-grid-test
2. npm install react-data-grid
3. Follow https://tailwindcss.com/docs/guides/create-react-app to add tailwind to the project
4. Put data-grid to App.js which is included in the zip file
5. The difference style if you comment out the "@tailwind base;" in index.css.

[data-grid-test.zip](https://github.com/user-attachments/files/18159024/data-grid-test.zip)

**Comment by amanmahajan7** [comment]
Can you create a codesandbox/stackblitz example?

**Comment by robert-luoqing** [comment]
https://codesandbox.io/p/devbox/react-data-grid-style-conflict-with-tailwind-sx8whr

**Comment by amanmahajan7** [comment]
RDG uses css layers and it seems like tailwind styles are unlayed in the above example and the following block overrides RDG styles

```
*, ::before, ::after {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: #e5e7eb;
```

Is this a setup issue as it looks like `tailwind` does have [layers ](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer). I am changing this issue to a discussion as it is not a bug in RDG

**Comment by oskarunt** [comment]
Any solution to this? Dealing with the same problem unfortunately :/

**Comment by ashu-shukla** [comment]
Even Treedatagrid is not working... it has to do something with how the CSS is working with tailwind v4. The shadow is gone and also the grids lines/borders as well.

**Reply by ashu-shukla** [reply]
The issue is that Tailwind CSS v4's Vite plugin uses LightningCSS, which incorrectly transforms **light-dark()**. 
I moved to compatible approach with color-scheme and CSS custom properties that work properly with **LightningCSS.**

so i for now removed ligt-dark function from the css and added 
```css
/* Root */
@layer rdg.Root {

/* Replace all light-dark() functions and split to dark and light color-scheme */
    --rdg-color: light-dark(#000, #ddd);
    --rdg-border-color: light-dark(#ddd, #444);
    --rdg-summary-border-color: light-dark(#aaa, #555);
...
* Light mode colors (default) */
    --rdg-color: #000;
    --rdg-border-color: #ddd;
    --rdg-summary-border-color: #aaa;
    --rdg-background-color: hsl(0deg 0% 100%);
....
@media (prefers-color-scheme: dark) {
.rdg-7-0-0-beta-58-ccd2e5d9:not(.rdg-light) {
      --rdg-color: #ddd;
      --rdg-border-color: #444;
      --rdg-summary-border-color: #555;
      --rdg-background-color: hsl(0deg 0% 13%);
...
} 
and default light
```
